# Generated by Django 4.2.6 on 2023-11-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_id',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
